/*
 * This file is generated by jOOQ.
 */
package ee.mikkelsaar.tables.records;


import ee.mikkelsaar.tables.Share;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShareRecord extends UpdatableRecordImpl<ShareRecord> implements Record22<Long, Long, String, String, String, String, String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Integer, Long, BigDecimal, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.share.id</code>.
     */
    public ShareRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.share.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.share.day</code>.
     */
    public ShareRecord setDay(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.share.day</code>.
     */
    public Long getDay() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.share.ticker</code>.
     */
    public ShareRecord setTicker(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.share.ticker</code>.
     */
    public String getTicker() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.share.name</code>.
     */
    public ShareRecord setName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.share.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.share.isin</code>.
     */
    public ShareRecord setIsin(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.share.isin</code>.
     */
    public String getIsin() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.share.currency</code>.
     */
    public ShareRecord setCurrency(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.share.currency</code>.
     */
    public String getCurrency() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.share.marketplace</code>.
     */
    public ShareRecord setMarketplace(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.share.marketplace</code>.
     */
    public String getMarketplace() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.share.list</code>.
     */
    public ShareRecord setList(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.share.list</code>.
     */
    public String getList() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.share.average_price</code>.
     */
    public ShareRecord setAveragePrice(BigDecimal value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.share.average_price</code>.
     */
    public BigDecimal getAveragePrice() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>public.share.open_price</code>.
     */
    public ShareRecord setOpenPrice(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.share.open_price</code>.
     */
    public BigDecimal getOpenPrice() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>public.share.high_price</code>.
     */
    public ShareRecord setHighPrice(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.share.high_price</code>.
     */
    public BigDecimal getHighPrice() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>public.share.low_price</code>.
     */
    public ShareRecord setLowPrice(BigDecimal value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.share.low_price</code>.
     */
    public BigDecimal getLowPrice() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>public.share.last_close_price</code>.
     */
    public ShareRecord setLastClosePrice(BigDecimal value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.share.last_close_price</code>.
     */
    public BigDecimal getLastClosePrice() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>public.share.last_price</code>.
     */
    public ShareRecord setLastPrice(BigDecimal value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.share.last_price</code>.
     */
    public BigDecimal getLastPrice() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for <code>public.share.price_change_percentage</code>.
     */
    public ShareRecord setPriceChangePercentage(BigDecimal value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.share.price_change_percentage</code>.
     */
    public BigDecimal getPriceChangePercentage() {
        return (BigDecimal) get(14);
    }

    /**
     * Setter for <code>public.share.best_bid</code>.
     */
    public ShareRecord setBestBid(BigDecimal value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.share.best_bid</code>.
     */
    public BigDecimal getBestBid() {
        return (BigDecimal) get(15);
    }

    /**
     * Setter for <code>public.share.best_ask</code>.
     */
    public ShareRecord setBestAsk(BigDecimal value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>public.share.best_ask</code>.
     */
    public BigDecimal getBestAsk() {
        return (BigDecimal) get(16);
    }

    /**
     * Setter for <code>public.share.trades</code>.
     */
    public ShareRecord setTrades(Integer value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>public.share.trades</code>.
     */
    public Integer getTrades() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>public.share.volume</code>.
     */
    public ShareRecord setVolume(Long value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>public.share.volume</code>.
     */
    public Long getVolume() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>public.share.turnover</code>.
     */
    public ShareRecord setTurnover(BigDecimal value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>public.share.turnover</code>.
     */
    public BigDecimal getTurnover() {
        return (BigDecimal) get(19);
    }

    /**
     * Setter for <code>public.share.industry</code>.
     */
    public ShareRecord setIndustry(String value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>public.share.industry</code>.
     */
    public String getIndustry() {
        return (String) get(20);
    }

    /**
     * Setter for <code>public.share.supersector</code>.
     */
    public ShareRecord setSupersector(String value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>public.share.supersector</code>.
     */
    public String getSupersector() {
        return (String) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row22<Long, Long, String, String, String, String, String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Integer, Long, BigDecimal, String, String> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    @Override
    public Row22<Long, Long, String, String, String, String, String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Integer, Long, BigDecimal, String, String> valuesRow() {
        return (Row22) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Share.SHARE.ID;
    }

    @Override
    public Field<Long> field2() {
        return Share.SHARE.DAY;
    }

    @Override
    public Field<String> field3() {
        return Share.SHARE.TICKER;
    }

    @Override
    public Field<String> field4() {
        return Share.SHARE.NAME;
    }

    @Override
    public Field<String> field5() {
        return Share.SHARE.ISIN;
    }

    @Override
    public Field<String> field6() {
        return Share.SHARE.CURRENCY;
    }

    @Override
    public Field<String> field7() {
        return Share.SHARE.MARKETPLACE;
    }

    @Override
    public Field<String> field8() {
        return Share.SHARE.LIST;
    }

    @Override
    public Field<BigDecimal> field9() {
        return Share.SHARE.AVERAGE_PRICE;
    }

    @Override
    public Field<BigDecimal> field10() {
        return Share.SHARE.OPEN_PRICE;
    }

    @Override
    public Field<BigDecimal> field11() {
        return Share.SHARE.HIGH_PRICE;
    }

    @Override
    public Field<BigDecimal> field12() {
        return Share.SHARE.LOW_PRICE;
    }

    @Override
    public Field<BigDecimal> field13() {
        return Share.SHARE.LAST_CLOSE_PRICE;
    }

    @Override
    public Field<BigDecimal> field14() {
        return Share.SHARE.LAST_PRICE;
    }

    @Override
    public Field<BigDecimal> field15() {
        return Share.SHARE.PRICE_CHANGE_PERCENTAGE;
    }

    @Override
    public Field<BigDecimal> field16() {
        return Share.SHARE.BEST_BID;
    }

    @Override
    public Field<BigDecimal> field17() {
        return Share.SHARE.BEST_ASK;
    }

    @Override
    public Field<Integer> field18() {
        return Share.SHARE.TRADES;
    }

    @Override
    public Field<Long> field19() {
        return Share.SHARE.VOLUME;
    }

    @Override
    public Field<BigDecimal> field20() {
        return Share.SHARE.TURNOVER;
    }

    @Override
    public Field<String> field21() {
        return Share.SHARE.INDUSTRY;
    }

    @Override
    public Field<String> field22() {
        return Share.SHARE.SUPERSECTOR;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getDay();
    }

    @Override
    public String component3() {
        return getTicker();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getIsin();
    }

    @Override
    public String component6() {
        return getCurrency();
    }

    @Override
    public String component7() {
        return getMarketplace();
    }

    @Override
    public String component8() {
        return getList();
    }

    @Override
    public BigDecimal component9() {
        return getAveragePrice();
    }

    @Override
    public BigDecimal component10() {
        return getOpenPrice();
    }

    @Override
    public BigDecimal component11() {
        return getHighPrice();
    }

    @Override
    public BigDecimal component12() {
        return getLowPrice();
    }

    @Override
    public BigDecimal component13() {
        return getLastClosePrice();
    }

    @Override
    public BigDecimal component14() {
        return getLastPrice();
    }

    @Override
    public BigDecimal component15() {
        return getPriceChangePercentage();
    }

    @Override
    public BigDecimal component16() {
        return getBestBid();
    }

    @Override
    public BigDecimal component17() {
        return getBestAsk();
    }

    @Override
    public Integer component18() {
        return getTrades();
    }

    @Override
    public Long component19() {
        return getVolume();
    }

    @Override
    public BigDecimal component20() {
        return getTurnover();
    }

    @Override
    public String component21() {
        return getIndustry();
    }

    @Override
    public String component22() {
        return getSupersector();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getDay();
    }

    @Override
    public String value3() {
        return getTicker();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getIsin();
    }

    @Override
    public String value6() {
        return getCurrency();
    }

    @Override
    public String value7() {
        return getMarketplace();
    }

    @Override
    public String value8() {
        return getList();
    }

    @Override
    public BigDecimal value9() {
        return getAveragePrice();
    }

    @Override
    public BigDecimal value10() {
        return getOpenPrice();
    }

    @Override
    public BigDecimal value11() {
        return getHighPrice();
    }

    @Override
    public BigDecimal value12() {
        return getLowPrice();
    }

    @Override
    public BigDecimal value13() {
        return getLastClosePrice();
    }

    @Override
    public BigDecimal value14() {
        return getLastPrice();
    }

    @Override
    public BigDecimal value15() {
        return getPriceChangePercentage();
    }

    @Override
    public BigDecimal value16() {
        return getBestBid();
    }

    @Override
    public BigDecimal value17() {
        return getBestAsk();
    }

    @Override
    public Integer value18() {
        return getTrades();
    }

    @Override
    public Long value19() {
        return getVolume();
    }

    @Override
    public BigDecimal value20() {
        return getTurnover();
    }

    @Override
    public String value21() {
        return getIndustry();
    }

    @Override
    public String value22() {
        return getSupersector();
    }

    @Override
    public ShareRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ShareRecord value2(Long value) {
        setDay(value);
        return this;
    }

    @Override
    public ShareRecord value3(String value) {
        setTicker(value);
        return this;
    }

    @Override
    public ShareRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public ShareRecord value5(String value) {
        setIsin(value);
        return this;
    }

    @Override
    public ShareRecord value6(String value) {
        setCurrency(value);
        return this;
    }

    @Override
    public ShareRecord value7(String value) {
        setMarketplace(value);
        return this;
    }

    @Override
    public ShareRecord value8(String value) {
        setList(value);
        return this;
    }

    @Override
    public ShareRecord value9(BigDecimal value) {
        setAveragePrice(value);
        return this;
    }

    @Override
    public ShareRecord value10(BigDecimal value) {
        setOpenPrice(value);
        return this;
    }

    @Override
    public ShareRecord value11(BigDecimal value) {
        setHighPrice(value);
        return this;
    }

    @Override
    public ShareRecord value12(BigDecimal value) {
        setLowPrice(value);
        return this;
    }

    @Override
    public ShareRecord value13(BigDecimal value) {
        setLastClosePrice(value);
        return this;
    }

    @Override
    public ShareRecord value14(BigDecimal value) {
        setLastPrice(value);
        return this;
    }

    @Override
    public ShareRecord value15(BigDecimal value) {
        setPriceChangePercentage(value);
        return this;
    }

    @Override
    public ShareRecord value16(BigDecimal value) {
        setBestBid(value);
        return this;
    }

    @Override
    public ShareRecord value17(BigDecimal value) {
        setBestAsk(value);
        return this;
    }

    @Override
    public ShareRecord value18(Integer value) {
        setTrades(value);
        return this;
    }

    @Override
    public ShareRecord value19(Long value) {
        setVolume(value);
        return this;
    }

    @Override
    public ShareRecord value20(BigDecimal value) {
        setTurnover(value);
        return this;
    }

    @Override
    public ShareRecord value21(String value) {
        setIndustry(value);
        return this;
    }

    @Override
    public ShareRecord value22(String value) {
        setSupersector(value);
        return this;
    }

    @Override
    public ShareRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, String value7, String value8, BigDecimal value9, BigDecimal value10, BigDecimal value11, BigDecimal value12, BigDecimal value13, BigDecimal value14, BigDecimal value15, BigDecimal value16, BigDecimal value17, Integer value18, Long value19, BigDecimal value20, String value21, String value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShareRecord
     */
    public ShareRecord() {
        super(Share.SHARE);
    }

    /**
     * Create a detached, initialised ShareRecord
     */
    public ShareRecord(Long id, Long day, String ticker, String name, String isin, String currency, String marketplace, String list, BigDecimal averagePrice, BigDecimal openPrice, BigDecimal highPrice, BigDecimal lowPrice, BigDecimal lastClosePrice, BigDecimal lastPrice, BigDecimal priceChangePercentage, BigDecimal bestBid, BigDecimal bestAsk, Integer trades, Long volume, BigDecimal turnover, String industry, String supersector) {
        super(Share.SHARE);

        setId(id);
        setDay(day);
        setTicker(ticker);
        setName(name);
        setIsin(isin);
        setCurrency(currency);
        setMarketplace(marketplace);
        setList(list);
        setAveragePrice(averagePrice);
        setOpenPrice(openPrice);
        setHighPrice(highPrice);
        setLowPrice(lowPrice);
        setLastClosePrice(lastClosePrice);
        setLastPrice(lastPrice);
        setPriceChangePercentage(priceChangePercentage);
        setBestBid(bestBid);
        setBestAsk(bestAsk);
        setTrades(trades);
        setVolume(volume);
        setTurnover(turnover);
        setIndustry(industry);
        setSupersector(supersector);
    }
}
