/*
 * This file is generated by jOOQ.
 */
package ee.mikkelsaar;


import ee.mikkelsaar.tables.Day;
import ee.mikkelsaar.tables.Share;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.day</code>.
     */
    public final Day DAY = Day.DAY;

    /**
     * The table <code>public.share</code>.
     */
    public final Share SHARE = Share.SHARE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.DAY_ID_SEQ,
            Sequences.SHARE_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Day.DAY,
            Share.SHARE);
    }
}
