/*
 * This file is generated by jOOQ.
 */
package ee.mikkelsaar;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.day_id_seq</code>
     */
    public static final Sequence<Long> DAY_ID_SEQ = Internal.createSequence("day_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.share_id_seq</code>
     */
    public static final Sequence<Long> SHARE_ID_SEQ = Internal.createSequence("share_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
