/*
 * This file is generated by jOOQ.
 */
package ee.mikkelsaar;


import ee.mikkelsaar.tables.Day;
import ee.mikkelsaar.tables.Share;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.day</code>.
     */
    public static final Day DAY = Day.DAY;

    /**
     * The table <code>public.share</code>.
     */
    public static final Share SHARE = Share.SHARE;
}
