/*
 * This file is generated by jOOQ.
 */
package ee.mikkelsaar.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Day implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private LocalDateTime date;

    public Day() {}

    public Day(Day value) {
        this.id = value.id;
        this.date = value.date;
    }

    public Day(
        Long          id,
        LocalDateTime date
    ) {
        this.id = id;
        this.date = date;
    }

    /**
     * Getter for <code>public.day.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.day.id</code>.
     */
    public Day setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.day.date</code>.
     */
    public LocalDateTime getDate() {
        return this.date;
    }

    /**
     * Setter for <code>public.day.date</code>.
     */
    public Day setDate(LocalDateTime date) {
        this.date = date;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Day other = (Day) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (date == null) {
            if (other.date != null)
                return false;
        }
        else if (!date.equals(other.date))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.date == null) ? 0 : this.date.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Day (");

        sb.append(id);
        sb.append(", ").append(date);

        sb.append(")");
        return sb.toString();
    }
}
